<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Charity extends \Entity\Charity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'orgId', 'ein', 'overallRtg', 'name', 'url_slug', 'freatured_text', 'overallScore', 'rank', 'tagLine', 'cityId', 'stateId', 'email', 'phoneNumber', 'webSite', 'address', 'address2', 'zipCode', 'description', 'userId', 'fileName', 'createdAt', 'highestPaidOfficerCompensation', 'programServicesAmount', 'fundRaisingCostsAmount', 'adminExpensesAmount', 'revenueAmount', 'highestPaidOfficerCompensationPercentile', 'programServicesPercentile', 'fundRaisingCostsPercentile', 'adminExpensesPercentile', 'revenuePercentile', 'executivePay', 'overallScorePercentile', 'overallEfficiency', 'overallEfficiencyPercentile', 'fundraisingEffectiveness', 'fundraisingEffectivenessPercentile', 'executiveProductivity', 'executiveProductivityPercentile', 'chiefExecSalary', 'chiefExecSalaryPercentile', 'isFeatured', 'updatedAt', 'mission_summary', 'mission_summary_user_id', 'imageFile', 'errors', 'overallScoreText', 'metaCache', '_admin_data', '_mission', '_missions', 'reviews', 'averageReview', 'featuredCharities', '_irs_eins', '_irs_990', '_irs_990ez', '_irs_990pf', '_irs_2012990', '_irs_2012990ez', '_irs_2012990pf', '_revenue', '_program_services', 'high_low_markers');
        }

        return array('__isInitialized__', 'id', 'orgId', 'ein', 'overallRtg', 'name', 'url_slug', 'freatured_text', 'overallScore', 'rank', 'tagLine', 'cityId', 'stateId', 'email', 'phoneNumber', 'webSite', 'address', 'address2', 'zipCode', 'description', 'userId', 'fileName', 'createdAt', 'highestPaidOfficerCompensation', 'programServicesAmount', 'fundRaisingCostsAmount', 'adminExpensesAmount', 'revenueAmount', 'highestPaidOfficerCompensationPercentile', 'programServicesPercentile', 'fundRaisingCostsPercentile', 'adminExpensesPercentile', 'revenuePercentile', 'executivePay', 'overallScorePercentile', 'overallEfficiency', 'overallEfficiencyPercentile', 'fundraisingEffectiveness', 'fundraisingEffectivenessPercentile', 'executiveProductivity', 'executiveProductivityPercentile', 'chiefExecSalary', 'chiefExecSalaryPercentile', 'isFeatured', 'updatedAt', 'mission_summary', 'mission_summary_user_id', 'imageFile', 'errors', 'overallScoreText', 'metaCache', '_admin_data', '_mission', '_missions', 'reviews', 'averageReview', 'featuredCharities', '_irs_eins', '_irs_990', '_irs_990ez', '_irs_990pf', '_irs_2012990', '_irs_2012990ez', '_irs_2012990pf', '_revenue', '_program_services', 'high_low_markers');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Charity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', array());

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function getLdJsonSchema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLdJsonSchema', array());

        return parent::getLdJsonSchema();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName($convert_case = 2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array($convert_case));

        return parent::getName($convert_case);
    }

    /**
     * {@inheritDoc}
     */
    public function getcharityText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getcharityText', array());

        return parent::getcharityText();
    }

    /**
     * {@inheritDoc}
     */
    public function getOverallRtg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverallRtg', array());

        return parent::getOverallRtg();
    }

    /**
     * {@inheritDoc}
     */
    public function setRank($rank)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRank', array($rank));

        return parent::setRank($rank);
    }

    /**
     * {@inheritDoc}
     */
    public function getTagLine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTagLine', array());

        return parent::getTagLine();
    }

    /**
     * {@inheritDoc}
     */
    public function similar($limit = 3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'similar', array($limit));

        return parent::similar($limit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCauseIds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCauseIds', array());

        return parent::getCauseIds();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', array());

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setEin($ein)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEin', array($ein));

        return parent::setEin($ein);
    }

    /**
     * {@inheritDoc}
     */
    public function setCityId($cityId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCityId', array($cityId));

        return parent::setCityId($cityId);
    }

    /**
     * {@inheritDoc}
     */
    public function setOverallRtg($overallRtg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOverallRtg', array($overallRtg));

        return parent::setOverallRtg($overallRtg);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgId($orgId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgId', array($orgId));

        return parent::setOrgId($orgId);
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function setStateId($stateId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStateId', array($stateId));

        return parent::setStateId($stateId);
    }

    /**
     * {@inheritDoc}
     */
    public function setTagLine($tagLine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTagLine', array($tagLine));

        return parent::setTagLine($tagLine);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phoneNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', array($phoneNumber));

        return parent::setPhoneNumber($phoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function setWebSite($webSite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebSite', array($webSite));

        return parent::setWebSite($webSite);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress2($address2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress2', array($address2));

        return parent::setAddress2($address2);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode($zipCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', array($zipCode));

        return parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile($imageFile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', array($imageFile));

        return parent::setImageFile($imageFile);
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', array($userId));

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getHighestPaidOfficerCompensationPercentile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHighestPaidOfficerCompensationPercentile', array());

        return parent::getHighestPaidOfficerCompensationPercentile();
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramServicesPercentile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramServicesPercentile', array());

        return parent::getProgramServicesPercentile();
    }

    /**
     * {@inheritDoc}
     */
    public function getFundRaisingCostsPercentile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFundRaisingCostsPercentile', array());

        return parent::getFundRaisingCostsPercentile();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminExpensesPercentile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminExpensesPercentile', array());

        return parent::getAdminExpensesPercentile();
    }

    /**
     * {@inheritDoc}
     */
    public function getRevenuePercentile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevenuePercentile', array());

        return parent::getRevenuePercentile();
    }

    /**
     * {@inheritDoc}
     */
    public function getHighestPaidOfficerCompensation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHighestPaidOfficerCompensation', array());

        return parent::getHighestPaidOfficerCompensation();
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramServicesAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramServicesAmount', array());

        return parent::getProgramServicesAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getFundRaisingCostsAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFundRaisingCostsAmount', array());

        return parent::getFundRaisingCostsAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminExpensesAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminExpensesAmount', array());

        return parent::getAdminExpensesAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getRevenueAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevenueAmount', array());

        return parent::getRevenueAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getHighestPaidOfficerCompensationStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHighestPaidOfficerCompensationStr', array());

        return parent::getHighestPaidOfficerCompensationStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getProgramServicesAmountStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProgramServicesAmountStr', array());

        return parent::getProgramServicesAmountStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getFundRaisingCostsAmountStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFundRaisingCostsAmountStr', array());

        return parent::getFundRaisingCostsAmountStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminExpensesAmountStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminExpensesAmountStr', array());

        return parent::getAdminExpensesAmountStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getRevenueAmountStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRevenueAmountStr', array());

        return parent::getRevenueAmountStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setHighestPaidOfficerCompensation($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHighestPaidOfficerCompensation', array($v));

        return parent::setHighestPaidOfficerCompensation($v);
    }

    /**
     * {@inheritDoc}
     */
    public function setProgramServicesAmount($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProgramServicesAmount', array($v));

        return parent::setProgramServicesAmount($v);
    }

    /**
     * {@inheritDoc}
     */
    public function setFundRaisingCostsAmount($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFundRaisingCostsAmount', array($v));

        return parent::setFundRaisingCostsAmount($v);
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminExpensesAmount($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminExpensesAmount', array($v));

        return parent::setAdminExpensesAmount($v);
    }

    /**
     * {@inheritDoc}
     */
    public function setRevenueAmount($v)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRevenueAmount', array($v));

        return parent::setRevenueAmount($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getFileName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFileName', array());

        return parent::getFileName();
    }

    /**
     * {@inheritDoc}
     */
    public function getErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getErrors', array());

        return parent::getErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function setFileName($fileName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFileName', array($fileName));

        return parent::setFileName($fileName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', array());

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getStateId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStateId', array());

        return parent::getStateId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCityId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCityId', array());

        return parent::getCityId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEin($formatted = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEin', array($formatted));

        return parent::getEin($formatted);
    }

    /**
     * {@inheritDoc}
     */
    public function hasFakeEin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasFakeEin', array());

        return parent::hasFakeEin();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebSite', array());

        return parent::getWebSite();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress2', array());

        return parent::getAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', array());

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getFollowers($limit = NULL, $offset = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFollowers', array($limit, $offset));

        return parent::getFollowers($limit, $offset);
    }

    /**
     * {@inheritDoc}
     */
    public function getOverallScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverallScore', array());

        return parent::getOverallScore();
    }

    /**
     * {@inheritDoc}
     */
    public function getOverallScorePercentage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverallScorePercentage', array());

        return parent::getOverallScorePercentage();
    }

    /**
     * {@inheritDoc}
     */
    public function setOverallScore($overallScore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOverallScore', array($overallScore));

        return parent::setOverallScore($overallScore);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgId', array());

        return parent::getOrgId();
    }

    /**
     * {@inheritDoc}
     */
    public function isReadyForDonation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isReadyForDonation', array());

        return parent::isReadyForDonation();
    }

    /**
     * {@inheritDoc}
     */
    public function getMetaValue($key)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetaValue', array($key));

        return parent::getMetaValue($key);
    }

    /**
     * {@inheritDoc}
     */
    public function setMeta($key, $value, $flush = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeta', array($key, $value, $flush));

        return parent::setMeta($key, $value, $flush);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminDataValue($field)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminDataValue', array($field));

        return parent::getAdminDataValue($field);
    }

    /**
     * {@inheritDoc}
     */
    public function getMissionSummary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissionSummary', array());

        return parent::getMissionSummary();
    }

    /**
     * {@inheritDoc}
     */
    public function getMission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMission', array());

        return parent::getMission();
    }

    /**
     * {@inheritDoc}
     */
    public function getMissions($limit = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissions', array($limit));

        return parent::getMissions($limit);
    }

    /**
     * {@inheritDoc}
     */
    public function setMissionSummary($mission_summary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMissionSummary', array($mission_summary));

        return parent::setMissionSummary($mission_summary);
    }

    /**
     * {@inheritDoc}
     */
    public function prepareChiefExecSalary($execName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prepareChiefExecSalary', array($execName));

        return parent::prepareChiefExecSalary($execName);
    }

    /**
     * {@inheritDoc}
     */
    public function getChiefExecSalary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChiefExecSalary', array());

        return parent::getChiefExecSalary();
    }

    /**
     * {@inheritDoc}
     */
    public function getChiefExecSalaryPercentile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChiefExecSalaryPercentile', array());

        return parent::getChiefExecSalaryPercentile();
    }

    /**
     * {@inheritDoc}
     */
    public function getChiefExecSalaryStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChiefExecSalaryStr', array());

        return parent::getChiefExecSalaryStr();
    }

    /**
     * {@inheritDoc}
     */
    public function percentilePrepare()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'percentilePrepare', array());

        return parent::percentilePrepare();
    }

    /**
     * {@inheritDoc}
     */
    public function calculateExecutivePay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateExecutivePay', array());

        return parent::calculateExecutivePay();
    }

    /**
     * {@inheritDoc}
     */
    public function calculateOverallEfficiencyAndFundraisingEffectivenessAndExecutiveProductivity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateOverallEfficiencyAndFundraisingEffectivenessAndExecutiveProductivity', array());

        return parent::calculateOverallEfficiencyAndFundraisingEffectivenessAndExecutiveProductivity();
    }

    /**
     * {@inheritDoc}
     */
    public function calculateOverallScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateOverallScore', array());

        return parent::calculateOverallScore();
    }

    /**
     * {@inheritDoc}
     */
    public function calculateOverallEfficiency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateOverallEfficiency', array());

        return parent::calculateOverallEfficiency();
    }

    /**
     * {@inheritDoc}
     */
    public function calculateFundraisingEffectiveness()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateFundraisingEffectiveness', array());

        return parent::calculateFundraisingEffectiveness();
    }

    /**
     * {@inheritDoc}
     */
    public function calculateExecutiveProductivity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calculateExecutiveProductivity', array());

        return parent::calculateExecutiveProductivity();
    }

    /**
     * {@inheritDoc}
     */
    public function custom_number_format($n, $precision = 3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'custom_number_format', array($n, $precision));

        return parent::custom_number_format($n, $precision);
    }

    /**
     * {@inheritDoc}
     */
    public function getOverallEfficiency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverallEfficiency', array());

        return parent::getOverallEfficiency();
    }

    /**
     * {@inheritDoc}
     */
    public function getOverallEfficiencyStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverallEfficiencyStr', array());

        return parent::getOverallEfficiencyStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getOverallEfficiencyPercentile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverallEfficiencyPercentile', array());

        return parent::getOverallEfficiencyPercentile();
    }

    /**
     * {@inheritDoc}
     */
    public function getFundraisingEffectiveness()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFundraisingEffectiveness', array());

        return parent::getFundraisingEffectiveness();
    }

    /**
     * {@inheritDoc}
     */
    public function getFundraisingEffectivenessStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFundraisingEffectivenessStr', array());

        return parent::getFundraisingEffectivenessStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getFundraisingEffectivenessPercentile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFundraisingEffectivenessPercentile', array());

        return parent::getFundraisingEffectivenessPercentile();
    }

    /**
     * {@inheritDoc}
     */
    public function getExecutiveProductivity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExecutiveProductivity', array());

        return parent::getExecutiveProductivity();
    }

    /**
     * {@inheritDoc}
     */
    public function getExecutiveProductivityStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExecutiveProductivityStr', array());

        return parent::getExecutiveProductivityStr();
    }

    /**
     * {@inheritDoc}
     */
    public function getExecutiveProductivityPercentile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExecutiveProductivityPercentile', array());

        return parent::getExecutiveProductivityPercentile();
    }

    /**
     * {@inheritDoc}
     */
    public function getOverallScorePercentile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverallScorePercentile', array());

        return parent::getOverallScorePercentile();
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlSlugOrId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlSlugOrId', array());

        return parent::getUrlSlugOrId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl($full = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array($full));

        return parent::getUrl($full);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', array());

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function getFeaturedText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeaturedText', array());

        return parent::getFeaturedText();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsFeatured()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsFeatured', array());

        return parent::getIsFeatured();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsFeatured($isFeatured)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsFeatured', array($isFeatured));

        return parent::setIsFeatured($isFeatured);
    }

    /**
     * {@inheritDoc}
     */
    public function setFeaturedText($text)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeaturedText', array($text));

        return parent::setFeaturedText($text);
    }

    /**
     * {@inheritDoc}
     */
    public function getKeywords()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKeywords', array());

        return parent::getKeywords();
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', array());

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function getCauses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCauses', array());

        return parent::getCauses();
    }

    /**
     * {@inheritDoc}
     */
    public function getCauseNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCauseNames', array());

        return parent::getCauseNames();
    }

    /**
     * {@inheritDoc}
     */
    public function hasReviews()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasReviews', array());

        return parent::hasReviews();
    }

    /**
     * {@inheritDoc}
     */
    public function getReviews()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviews', array());

        return parent::getReviews();
    }

    /**
     * {@inheritDoc}
     */
    public function getAverageReview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAverageReview', array());

        return parent::getAverageReview();
    }

    /**
     * {@inheritDoc}
     */
    public function followersCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'followersCount', array());

        return parent::followersCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAtDt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAtDt', array($updatedAt));

        return parent::setUpdatedAtDt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAtDt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAtDt', array());

        return parent::getUpdatedAtDt();
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', array());

        return parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', array());

        return parent::onPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCityName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCityName', array());

        return parent::getCityName();
    }

    /**
     * {@inheritDoc}
     */
    public function getStateFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStateFullName', array());

        return parent::getStateFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function getStateName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStateName', array());

        return parent::getStateName();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreRemove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreRemove', array());

        return parent::onPreRemove();
    }

    /**
     * {@inheritDoc}
     */
    public function showOverallScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'showOverallScore', array());

        return parent::showOverallScore();
    }

    /**
     * {@inheritDoc}
     */
    public function isFromCharityNavigator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFromCharityNavigator', array());

        return parent::isFromCharityNavigator();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageUrl', array());

        return parent::getImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function changeUrlSlug($new_url_slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'changeUrlSlug', array($new_url_slug));

        return parent::changeUrlSlug($new_url_slug);
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlSlug($url_slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlSlug', array($url_slug));

        return parent::setUrlSlug($url_slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlSlug', array());

        return parent::getUrlSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setMissionSummaryUserId($mission_summary_user_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMissionSummaryUserId', array($mission_summary_user_id));

        return parent::setMissionSummaryUserId($mission_summary_user_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getMissionSummaryUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissionSummaryUserId', array());

        return parent::getMissionSummaryUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMissionSummaryUser(\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMissionSummaryUser', array($user));

        return parent::setMissionSummaryUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getMissionSummaryUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissionSummaryUser', array());

        return parent::getMissionSummaryUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getCitizenData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCitizenData', array());

        return parent::getCitizenData();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsEins()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsEins', array());

        return parent::getIrsEins();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrs2012990()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrs2012990', array());

        return parent::getIrs2012990();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrs2012990ez()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrs2012990ez', array());

        return parent::getIrs2012990ez();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrs2012990pf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrs2012990pf', array());

        return parent::getIrs2012990pf();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrs990()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrs990', array());

        return parent::getIrs990();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrs990ez()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrs990ez', array());

        return parent::getIrs990ez();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrs990pf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrs990pf', array());

        return parent::getIrs990pf();
    }

    /**
     * {@inheritDoc}
     */
    public function getLatestIrsEinsField($field_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatestIrsEinsField', array($field_name));

        return parent::getLatestIrsEinsField($field_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatestIrs9902012990Field($field_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatestIrs9902012990Field', array($field_name));

        return parent::getLatestIrs9902012990Field($field_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatestIrsField($field_name, $format_to_dollars = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatestIrsField', array($field_name, $format_to_dollars));

        return parent::getLatestIrsField($field_name, $format_to_dollars);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercentageOfRevenue($value, $return_string = true, $return_rounded = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercentageOfRevenue', array($value, $return_string, $return_rounded));

        return parent::getPercentageOfRevenue($value, $return_string, $return_rounded);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsProgramServicesAsPercentageOfTotalFunctionalExpenses($raw_result = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsProgramServicesAsPercentageOfTotalFunctionalExpenses', array($raw_result));

        return parent::getIrsProgramServicesAsPercentageOfTotalFunctionalExpenses($raw_result);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsAssets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsAssets', array());

        return parent::getIrsAssets();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsIncome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsIncome', array());

        return parent::getIrsIncome();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsRevenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsRevenue', array());

        return parent::getIrsRevenue();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsRulingDate($format_to_dollars = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsRulingDate', array($format_to_dollars));

        return parent::getIrsRulingDate($format_to_dollars);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsTotalContributions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsTotalContributions', array());

        return parent::getIrsTotalContributions();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsTotalContributionsPercentageOfRevenue($return_string = true, $return_rounded = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsTotalContributionsPercentageOfRevenue', array($return_string, $return_rounded));

        return parent::getIrsTotalContributionsPercentageOfRevenue($return_string, $return_rounded);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsProgramServiceRevenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsProgramServiceRevenue', array());

        return parent::getIrsProgramServiceRevenue();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsInvestmentIncome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsInvestmentIncome', array());

        return parent::getIrsInvestmentIncome();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsGrossFundraising()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsGrossFundraising', array());

        return parent::getIrsGrossFundraising();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsFundraisingExpenses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsFundraisingExpenses', array());

        return parent::getIrsFundraisingExpenses();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsFundraisingExpensesPercentageOfRevenue($return_string = true, $return_rounded = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsFundraisingExpensesPercentageOfRevenue', array($return_string, $return_rounded));

        return parent::getIrsFundraisingExpensesPercentageOfRevenue($return_string, $return_rounded);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsTotalFunctionalExpenses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsTotalFunctionalExpenses', array());

        return parent::getIrsTotalFunctionalExpenses();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsTotalFunctionalExpensesPercentageOfRevenue($return_string = true, $return_rounded = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsTotalFunctionalExpensesPercentageOfRevenue', array($return_string, $return_rounded));

        return parent::getIrsTotalFunctionalExpensesPercentageOfRevenue($return_string, $return_rounded);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsProFundraisingFees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsProFundraisingFees', array());

        return parent::getIrsProFundraisingFees();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsProFundraisingFeesPercentageOfRevenue($return_string = true, $return_rounded = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsProFundraisingFeesPercentageOfRevenue', array($return_string, $return_rounded));

        return parent::getIrsProFundraisingFeesPercentageOfRevenue($return_string, $return_rounded);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsTotalRevenue($format_to_dollars = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsTotalRevenue', array($format_to_dollars));

        return parent::getIrsTotalRevenue($format_to_dollars);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsCompensationOfCurrentOfficers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsCompensationOfCurrentOfficers', array());

        return parent::getIrsCompensationOfCurrentOfficers();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsCompensationOfCurrentOfficersPercentageOfRevenue($return_string = true, $return_rounded = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsCompensationOfCurrentOfficersPercentageOfRevenue', array($return_string, $return_rounded));

        return parent::getIrsCompensationOfCurrentOfficersPercentageOfRevenue($return_string, $return_rounded);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsAdvertisingAndPromotionsPercentageOfRevenue($return_string = true, $return_rounded = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsAdvertisingAndPromotionsPercentageOfRevenue', array($return_string, $return_rounded));

        return parent::getIrsAdvertisingAndPromotionsPercentageOfRevenue($return_string, $return_rounded);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsOfficeExpensesPercentageOfRevenue($return_string = true, $return_rounded = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsOfficeExpensesPercentageOfRevenue', array($return_string, $return_rounded));

        return parent::getIrsOfficeExpensesPercentageOfRevenue($return_string, $return_rounded);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsInformationTechnologyPercentageOfRevenue($return_string = true, $return_rounded = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsInformationTechnologyPercentageOfRevenue', array($return_string, $return_rounded));

        return parent::getIrsInformationTechnologyPercentageOfRevenue($return_string, $return_rounded);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsTravelPercentageOfRevenue($return_string = true, $return_rounded = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsTravelPercentageOfRevenue', array($return_string, $return_rounded));

        return parent::getIrsTravelPercentageOfRevenue($return_string, $return_rounded);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsConferencesConventionsMeetingsPercentageOfRevenue($return_string = true, $return_rounded = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsConferencesConventionsMeetingsPercentageOfRevenue', array($return_string, $return_rounded));

        return parent::getIrsConferencesConventionsMeetingsPercentageOfRevenue($return_string, $return_rounded);
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsStreetAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsStreetAddress', array());

        return parent::getIrsStreetAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsCity', array());

        return parent::getIrsCity();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsState', array());

        return parent::getIrsState();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsZipcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsZipcode', array());

        return parent::getIrsZipcode();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsStateFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsStateFullName', array());

        return parent::getIrsStateFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function getSearchDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSearchDesc', array());

        return parent::getSearchDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function getIrsInfoFromDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIrsInfoFromDesc', array());

        return parent::getIrsInfoFromDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function getHighLow($field, $value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHighLow', array($field, $value));

        return parent::getHighLow($field, $value);
    }

    /**
     * {@inheritDoc}
     */
    public function getVolunteeringOpportunities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolunteeringOpportunities', array());

        return parent::getVolunteeringOpportunities();
    }

    /**
     * {@inheritDoc}
     */
    public function getVolunteeringOpportunitiesReviewsCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolunteeringOpportunitiesReviewsCount', array());

        return parent::getVolunteeringOpportunitiesReviewsCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserReviewedVolunteeringOpportunities(\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserReviewedVolunteeringOpportunities', array($user));

        return parent::getUserReviewedVolunteeringOpportunities($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrOfEventsForMonth(\DateTime $dt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrOfEventsForMonth', array($dt));

        return parent::getNrOfEventsForMonth($dt);
    }

    /**
     * {@inheritDoc}
     */
    public function hasCover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasCover', array());

        return parent::hasCover();
    }

    /**
     * {@inheritDoc}
     */
    public function getCover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCover', array());

        return parent::getCover();
    }

    /**
     * {@inheritDoc}
     */
    public function deleteCover()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deleteCover', array());

        return parent::deleteCover();
    }

    /**
     * {@inheritDoc}
     */
    public function hasLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasLogo', array());

        return parent::hasLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', array());

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function deleteLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'deleteLogo', array());

        return parent::deleteLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function get_class_without_namespace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_class_without_namespace', array());

        return parent::get_class_without_namespace();
    }

}
