<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FAQ extends \Entity\FAQ implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'fq_ques', 'fq_ans', 'fq_filter', 'fq_order', 'create_date', 'is_active');
        }

        return array('__isInitialized__', 'id', 'fq_ques', 'fq_ans', 'fq_filter', 'fq_order', 'create_date', 'is_active');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FAQ $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIsActive($is_active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', array($is_active));

        return parent::setIsActive($is_active);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', array());

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate($create_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', array($create_date));

        return parent::setCreateDate($create_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', array());

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDateDt(\DateTime $create_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDateDt', array($create_date));

        return parent::setCreateDateDt($create_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDateDt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDateDt', array());

        return parent::getCreateDateDt();
    }

    /**
     * {@inheritDoc}
     */
    public function setFqAns($fq_ans)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFqAns', array($fq_ans));

        return parent::setFqAns($fq_ans);
    }

    /**
     * {@inheritDoc}
     */
    public function getFqAns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFqAns', array());

        return parent::getFqAns();
    }

    /**
     * {@inheritDoc}
     */
    public function setFqFilter($fq_filter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFqFilter', array($fq_filter));

        return parent::setFqFilter($fq_filter);
    }

    /**
     * {@inheritDoc}
     */
    public function getFqFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFqFilter', array());

        return parent::getFqFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function setFqQues($fq_ques)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFqQues', array($fq_ques));

        return parent::setFqQues($fq_ques);
    }

    /**
     * {@inheritDoc}
     */
    public function getFqQues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFqQues', array());

        return parent::getFqQues();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFqOrder($fq_order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFqOrder', array($fq_order));

        return parent::setFqOrder($fq_order);
    }

    /**
     * {@inheritDoc}
     */
    public function getFqOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFqOrder', array());

        return parent::getFqOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function get_class_without_namespace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_class_without_namespace', array());

        return parent::get_class_without_namespace();
    }

}
