<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Irs2012990pf extends \Entity\Irs2012990pf implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'ein', 'taxPrd', 'eostatus', 'taxYr', 'operatingcd', 'assetcdgen', 'transinccd', 'subcd', 'grscontrgifts', 'intrstrvnue', 'dividndsamt', 'totexcapgn', 'totexcapls', 'grsprofitbus', 'otherincamt', 'compofficers', 'contrpdpbks', 'totrcptperbks', 'totexpnspbks', 'excessrcpts', 'totexpnsexempt', 'netinvstinc', 'totaxpyr', 'adjnetinc', 'totassetsend', 'invstgovtoblig', 'invstcorpstk', 'invstcorpbnd', 'totinvstsec', 'totliabend', 'fairmrktvalamt', 'undistribincyr', 'cmpmininvstret', 'sec4940notxcd', 'sec4940redtxcd', 'infleg', 'contractncd', 'claimstatcd', 'propexchcd', 'brwlndmnycd', 'furngoodscd', 'paidcmpncd', 'trnsothasstscd', 'agremkpaycd', 'undistrinccd', 'dirindirintcd', 'invstjexmptcd', 'propgndacd', 'excesshldcd', 'grntindivcd', 'nchrtygrntcd', 'nreligiouscd', 'grsrents', 'costsold', 'totrcptnetinc', 'trcptadjnetinc', 'topradmnexpnsa', 'topradmnexpnsb', 'topradmnexpnsd', 'totexpnsnetinc', 'totexpnsadjnet', 'othrcashamt', 'mrtgloans', 'othrinvstend', 'fairmrktvaleoy', 'mrtgnotespay', 'tfundnworth', 'invstexcisetx', 'sect511tx', 'subtitleatx', 'esttaxcr', 'txwithldsrc', 'txpaidf2758', 'erronbkupwthld', 'estpnlty', 'balduopt', 'crelamt', 'tfairmrktunuse', 'distribamt', 'adjnetinccola', 'adjnetinccolb', 'adjnetinccolc', 'adjnetinccold', 'adjnetinctot', 'qlfydistriba', 'qlfydistribb', 'qlfydistribc', 'qlfydistribd', 'qlfydistribtot', 'valassetscola', 'valassetscolb', 'valassetscolc', 'valassetscold', 'valassetstot', 'qlfyasseta', 'qlfyassetb', 'qlfyassetc', 'qlfyassetd', 'qlfyassettot', 'endwmntscola', 'endwmntscolb', 'endwmntscolc', 'endwmntscold', 'endwmntstot', 'totsuprtcola', 'totsuprtcolb', 'totsuprtcolc', 'totsuprtcold', 'totsuprttot', 'pubsuprtcola', 'pubsuprtcolb', 'pubsuprtcolc', 'pubsuprtcold', 'pubsuprttot', 'grsinvstinca', 'grsinvstincb', 'grsinvstincc', 'grsinvstincd', 'grsinvstinctot');
        }

        return array('__isInitialized__', 'id', 'ein', 'taxPrd', 'eostatus', 'taxYr', 'operatingcd', 'assetcdgen', 'transinccd', 'subcd', 'grscontrgifts', 'intrstrvnue', 'dividndsamt', 'totexcapgn', 'totexcapls', 'grsprofitbus', 'otherincamt', 'compofficers', 'contrpdpbks', 'totrcptperbks', 'totexpnspbks', 'excessrcpts', 'totexpnsexempt', 'netinvstinc', 'totaxpyr', 'adjnetinc', 'totassetsend', 'invstgovtoblig', 'invstcorpstk', 'invstcorpbnd', 'totinvstsec', 'totliabend', 'fairmrktvalamt', 'undistribincyr', 'cmpmininvstret', 'sec4940notxcd', 'sec4940redtxcd', 'infleg', 'contractncd', 'claimstatcd', 'propexchcd', 'brwlndmnycd', 'furngoodscd', 'paidcmpncd', 'trnsothasstscd', 'agremkpaycd', 'undistrinccd', 'dirindirintcd', 'invstjexmptcd', 'propgndacd', 'excesshldcd', 'grntindivcd', 'nchrtygrntcd', 'nreligiouscd', 'grsrents', 'costsold', 'totrcptnetinc', 'trcptadjnetinc', 'topradmnexpnsa', 'topradmnexpnsb', 'topradmnexpnsd', 'totexpnsnetinc', 'totexpnsadjnet', 'othrcashamt', 'mrtgloans', 'othrinvstend', 'fairmrktvaleoy', 'mrtgnotespay', 'tfundnworth', 'invstexcisetx', 'sect511tx', 'subtitleatx', 'esttaxcr', 'txwithldsrc', 'txpaidf2758', 'erronbkupwthld', 'estpnlty', 'balduopt', 'crelamt', 'tfairmrktunuse', 'distribamt', 'adjnetinccola', 'adjnetinccolb', 'adjnetinccolc', 'adjnetinccold', 'adjnetinctot', 'qlfydistriba', 'qlfydistribb', 'qlfydistribc', 'qlfydistribd', 'qlfydistribtot', 'valassetscola', 'valassetscolb', 'valassetscolc', 'valassetscold', 'valassetstot', 'qlfyasseta', 'qlfyassetb', 'qlfyassetc', 'qlfyassetd', 'qlfyassettot', 'endwmntscola', 'endwmntscolb', 'endwmntscolc', 'endwmntscold', 'endwmntstot', 'totsuprtcola', 'totsuprtcolb', 'totsuprtcolc', 'totsuprtcold', 'totsuprttot', 'pubsuprtcola', 'pubsuprtcolb', 'pubsuprtcolc', 'pubsuprtcold', 'pubsuprttot', 'grsinvstinca', 'grsinvstincb', 'grsinvstincc', 'grsinvstincd', 'grsinvstinctot');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Irs2012990pf $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setAdjnetinc($adjnetinc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdjnetinc', array($adjnetinc));

        return parent::setAdjnetinc($adjnetinc);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdjnetinc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdjnetinc', array());

        return parent::getAdjnetinc();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdjnetinccola($adjnetinccola)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdjnetinccola', array($adjnetinccola));

        return parent::setAdjnetinccola($adjnetinccola);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdjnetinccola()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdjnetinccola', array());

        return parent::getAdjnetinccola();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdjnetinccolb($adjnetinccolb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdjnetinccolb', array($adjnetinccolb));

        return parent::setAdjnetinccolb($adjnetinccolb);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdjnetinccolb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdjnetinccolb', array());

        return parent::getAdjnetinccolb();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdjnetinccolc($adjnetinccolc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdjnetinccolc', array($adjnetinccolc));

        return parent::setAdjnetinccolc($adjnetinccolc);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdjnetinccolc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdjnetinccolc', array());

        return parent::getAdjnetinccolc();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdjnetinccold($adjnetinccold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdjnetinccold', array($adjnetinccold));

        return parent::setAdjnetinccold($adjnetinccold);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdjnetinccold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdjnetinccold', array());

        return parent::getAdjnetinccold();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdjnetinctot($adjnetinctot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdjnetinctot', array($adjnetinctot));

        return parent::setAdjnetinctot($adjnetinctot);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdjnetinctot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdjnetinctot', array());

        return parent::getAdjnetinctot();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgremkpaycd($agremkpaycd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgremkpaycd', array($agremkpaycd));

        return parent::setAgremkpaycd($agremkpaycd);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgremkpaycd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgremkpaycd', array());

        return parent::getAgremkpaycd();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssetcdgen($assetcdgen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssetcdgen', array($assetcdgen));

        return parent::setAssetcdgen($assetcdgen);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssetcdgen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssetcdgen', array());

        return parent::getAssetcdgen();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalduopt($balduopt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalduopt', array($balduopt));

        return parent::setBalduopt($balduopt);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalduopt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalduopt', array());

        return parent::getBalduopt();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrwlndmnycd($brwlndmnycd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrwlndmnycd', array($brwlndmnycd));

        return parent::setBrwlndmnycd($brwlndmnycd);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrwlndmnycd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrwlndmnycd', array());

        return parent::getBrwlndmnycd();
    }

    /**
     * {@inheritDoc}
     */
    public function setClaimstatcd($claimstatcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClaimstatcd', array($claimstatcd));

        return parent::setClaimstatcd($claimstatcd);
    }

    /**
     * {@inheritDoc}
     */
    public function getClaimstatcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClaimstatcd', array());

        return parent::getClaimstatcd();
    }

    /**
     * {@inheritDoc}
     */
    public function setCmpmininvstret($cmpmininvstret)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCmpmininvstret', array($cmpmininvstret));

        return parent::setCmpmininvstret($cmpmininvstret);
    }

    /**
     * {@inheritDoc}
     */
    public function getCmpmininvstret()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCmpmininvstret', array());

        return parent::getCmpmininvstret();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompofficers($compofficers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompofficers', array($compofficers));

        return parent::setCompofficers($compofficers);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompofficers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompofficers', array());

        return parent::getCompofficers();
    }

    /**
     * {@inheritDoc}
     */
    public function setContractncd($contractncd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContractncd', array($contractncd));

        return parent::setContractncd($contractncd);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractncd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractncd', array());

        return parent::getContractncd();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrpdpbks($contrpdpbks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrpdpbks', array($contrpdpbks));

        return parent::setContrpdpbks($contrpdpbks);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrpdpbks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrpdpbks', array());

        return parent::getContrpdpbks();
    }

    /**
     * {@inheritDoc}
     */
    public function setCostsold($costsold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCostsold', array($costsold));

        return parent::setCostsold($costsold);
    }

    /**
     * {@inheritDoc}
     */
    public function getCostsold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostsold', array());

        return parent::getCostsold();
    }

    /**
     * {@inheritDoc}
     */
    public function setCrelamt($crelamt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCrelamt', array($crelamt));

        return parent::setCrelamt($crelamt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCrelamt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCrelamt', array());

        return parent::getCrelamt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirindirintcd($dirindirintcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirindirintcd', array($dirindirintcd));

        return parent::setDirindirintcd($dirindirintcd);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirindirintcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirindirintcd', array());

        return parent::getDirindirintcd();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistribamt($distribamt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistribamt', array($distribamt));

        return parent::setDistribamt($distribamt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistribamt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistribamt', array());

        return parent::getDistribamt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDividndsamt($dividndsamt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDividndsamt', array($dividndsamt));

        return parent::setDividndsamt($dividndsamt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDividndsamt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDividndsamt', array());

        return parent::getDividndsamt();
    }

    /**
     * {@inheritDoc}
     */
    public function setEin($ein)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEin', array($ein));

        return parent::setEin($ein);
    }

    /**
     * {@inheritDoc}
     */
    public function getEin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEin', array());

        return parent::getEin();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndwmntscola($endwmntscola)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndwmntscola', array($endwmntscola));

        return parent::setEndwmntscola($endwmntscola);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndwmntscola()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndwmntscola', array());

        return parent::getEndwmntscola();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndwmntscolb($endwmntscolb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndwmntscolb', array($endwmntscolb));

        return parent::setEndwmntscolb($endwmntscolb);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndwmntscolb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndwmntscolb', array());

        return parent::getEndwmntscolb();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndwmntscolc($endwmntscolc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndwmntscolc', array($endwmntscolc));

        return parent::setEndwmntscolc($endwmntscolc);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndwmntscolc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndwmntscolc', array());

        return parent::getEndwmntscolc();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndwmntscold($endwmntscold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndwmntscold', array($endwmntscold));

        return parent::setEndwmntscold($endwmntscold);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndwmntscold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndwmntscold', array());

        return parent::getEndwmntscold();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndwmntstot($endwmntstot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndwmntstot', array($endwmntstot));

        return parent::setEndwmntstot($endwmntstot);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndwmntstot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndwmntstot', array());

        return parent::getEndwmntstot();
    }

    /**
     * {@inheritDoc}
     */
    public function setEostatus($eostatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEostatus', array($eostatus));

        return parent::setEostatus($eostatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getEostatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEostatus', array());

        return parent::getEostatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setErronbkupwthld($erronbkupwthld)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setErronbkupwthld', array($erronbkupwthld));

        return parent::setErronbkupwthld($erronbkupwthld);
    }

    /**
     * {@inheritDoc}
     */
    public function getErronbkupwthld()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getErronbkupwthld', array());

        return parent::getErronbkupwthld();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstpnlty($estpnlty)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstpnlty', array($estpnlty));

        return parent::setEstpnlty($estpnlty);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstpnlty()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstpnlty', array());

        return parent::getEstpnlty();
    }

    /**
     * {@inheritDoc}
     */
    public function setEsttaxcr($esttaxcr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEsttaxcr', array($esttaxcr));

        return parent::setEsttaxcr($esttaxcr);
    }

    /**
     * {@inheritDoc}
     */
    public function getEsttaxcr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEsttaxcr', array());

        return parent::getEsttaxcr();
    }

    /**
     * {@inheritDoc}
     */
    public function setExcesshldcd($excesshldcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExcesshldcd', array($excesshldcd));

        return parent::setExcesshldcd($excesshldcd);
    }

    /**
     * {@inheritDoc}
     */
    public function getExcesshldcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcesshldcd', array());

        return parent::getExcesshldcd();
    }

    /**
     * {@inheritDoc}
     */
    public function setExcessrcpts($excessrcpts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExcessrcpts', array($excessrcpts));

        return parent::setExcessrcpts($excessrcpts);
    }

    /**
     * {@inheritDoc}
     */
    public function getExcessrcpts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcessrcpts', array());

        return parent::getExcessrcpts();
    }

    /**
     * {@inheritDoc}
     */
    public function setFairmrktvalamt($fairmrktvalamt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFairmrktvalamt', array($fairmrktvalamt));

        return parent::setFairmrktvalamt($fairmrktvalamt);
    }

    /**
     * {@inheritDoc}
     */
    public function getFairmrktvalamt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFairmrktvalamt', array());

        return parent::getFairmrktvalamt();
    }

    /**
     * {@inheritDoc}
     */
    public function setFairmrktvaleoy($fairmrktvaleoy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFairmrktvaleoy', array($fairmrktvaleoy));

        return parent::setFairmrktvaleoy($fairmrktvaleoy);
    }

    /**
     * {@inheritDoc}
     */
    public function getFairmrktvaleoy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFairmrktvaleoy', array());

        return parent::getFairmrktvaleoy();
    }

    /**
     * {@inheritDoc}
     */
    public function setFurngoodscd($furngoodscd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFurngoodscd', array($furngoodscd));

        return parent::setFurngoodscd($furngoodscd);
    }

    /**
     * {@inheritDoc}
     */
    public function getFurngoodscd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFurngoodscd', array());

        return parent::getFurngoodscd();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrntindivcd($grntindivcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrntindivcd', array($grntindivcd));

        return parent::setGrntindivcd($grntindivcd);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrntindivcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrntindivcd', array());

        return parent::getGrntindivcd();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrscontrgifts($grscontrgifts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrscontrgifts', array($grscontrgifts));

        return parent::setGrscontrgifts($grscontrgifts);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrscontrgifts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrscontrgifts', array());

        return parent::getGrscontrgifts();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsinvstinca($grsinvstinca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsinvstinca', array($grsinvstinca));

        return parent::setGrsinvstinca($grsinvstinca);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsinvstinca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsinvstinca', array());

        return parent::getGrsinvstinca();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsinvstincb($grsinvstincb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsinvstincb', array($grsinvstincb));

        return parent::setGrsinvstincb($grsinvstincb);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsinvstincb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsinvstincb', array());

        return parent::getGrsinvstincb();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsinvstincc($grsinvstincc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsinvstincc', array($grsinvstincc));

        return parent::setGrsinvstincc($grsinvstincc);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsinvstincc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsinvstincc', array());

        return parent::getGrsinvstincc();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsinvstincd($grsinvstincd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsinvstincd', array($grsinvstincd));

        return parent::setGrsinvstincd($grsinvstincd);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsinvstincd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsinvstincd', array());

        return parent::getGrsinvstincd();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsinvstinctot($grsinvstinctot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsinvstinctot', array($grsinvstinctot));

        return parent::setGrsinvstinctot($grsinvstinctot);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsinvstinctot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsinvstinctot', array());

        return parent::getGrsinvstinctot();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsprofitbus($grsprofitbus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsprofitbus', array($grsprofitbus));

        return parent::setGrsprofitbus($grsprofitbus);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsprofitbus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsprofitbus', array());

        return parent::getGrsprofitbus();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsrents($grsrents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsrents', array($grsrents));

        return parent::setGrsrents($grsrents);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsrents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsrents', array());

        return parent::getGrsrents();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfleg($infleg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfleg', array($infleg));

        return parent::setInfleg($infleg);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfleg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfleg', array());

        return parent::getInfleg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntrstrvnue($intrstrvnue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntrstrvnue', array($intrstrvnue));

        return parent::setIntrstrvnue($intrstrvnue);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntrstrvnue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntrstrvnue', array());

        return parent::getIntrstrvnue();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvstcorpbnd($invstcorpbnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvstcorpbnd', array($invstcorpbnd));

        return parent::setInvstcorpbnd($invstcorpbnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvstcorpbnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvstcorpbnd', array());

        return parent::getInvstcorpbnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvstcorpstk($invstcorpstk)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvstcorpstk', array($invstcorpstk));

        return parent::setInvstcorpstk($invstcorpstk);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvstcorpstk()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvstcorpstk', array());

        return parent::getInvstcorpstk();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvstexcisetx($invstexcisetx)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvstexcisetx', array($invstexcisetx));

        return parent::setInvstexcisetx($invstexcisetx);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvstexcisetx()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvstexcisetx', array());

        return parent::getInvstexcisetx();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvstgovtoblig($invstgovtoblig)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvstgovtoblig', array($invstgovtoblig));

        return parent::setInvstgovtoblig($invstgovtoblig);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvstgovtoblig()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvstgovtoblig', array());

        return parent::getInvstgovtoblig();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvstjexmptcd($invstjexmptcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvstjexmptcd', array($invstjexmptcd));

        return parent::setInvstjexmptcd($invstjexmptcd);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvstjexmptcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvstjexmptcd', array());

        return parent::getInvstjexmptcd();
    }

    /**
     * {@inheritDoc}
     */
    public function setMrtgloans($mrtgloans)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMrtgloans', array($mrtgloans));

        return parent::setMrtgloans($mrtgloans);
    }

    /**
     * {@inheritDoc}
     */
    public function getMrtgloans()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMrtgloans', array());

        return parent::getMrtgloans();
    }

    /**
     * {@inheritDoc}
     */
    public function setMrtgnotespay($mrtgnotespay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMrtgnotespay', array($mrtgnotespay));

        return parent::setMrtgnotespay($mrtgnotespay);
    }

    /**
     * {@inheritDoc}
     */
    public function getMrtgnotespay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMrtgnotespay', array());

        return parent::getMrtgnotespay();
    }

    /**
     * {@inheritDoc}
     */
    public function setNchrtygrntcd($nchrtygrntcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNchrtygrntcd', array($nchrtygrntcd));

        return parent::setNchrtygrntcd($nchrtygrntcd);
    }

    /**
     * {@inheritDoc}
     */
    public function getNchrtygrntcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNchrtygrntcd', array());

        return parent::getNchrtygrntcd();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetinvstinc($netinvstinc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetinvstinc', array($netinvstinc));

        return parent::setNetinvstinc($netinvstinc);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetinvstinc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetinvstinc', array());

        return parent::getNetinvstinc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNreligiouscd($nreligiouscd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNreligiouscd', array($nreligiouscd));

        return parent::setNreligiouscd($nreligiouscd);
    }

    /**
     * {@inheritDoc}
     */
    public function getNreligiouscd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNreligiouscd', array());

        return parent::getNreligiouscd();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperatingcd($operatingcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperatingcd', array($operatingcd));

        return parent::setOperatingcd($operatingcd);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperatingcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperatingcd', array());

        return parent::getOperatingcd();
    }

    /**
     * {@inheritDoc}
     */
    public function setOtherincamt($otherincamt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOtherincamt', array($otherincamt));

        return parent::setOtherincamt($otherincamt);
    }

    /**
     * {@inheritDoc}
     */
    public function getOtherincamt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOtherincamt', array());

        return parent::getOtherincamt();
    }

    /**
     * {@inheritDoc}
     */
    public function setOthrcashamt($othrcashamt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOthrcashamt', array($othrcashamt));

        return parent::setOthrcashamt($othrcashamt);
    }

    /**
     * {@inheritDoc}
     */
    public function getOthrcashamt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOthrcashamt', array());

        return parent::getOthrcashamt();
    }

    /**
     * {@inheritDoc}
     */
    public function setOthrinvstend($othrinvstend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOthrinvstend', array($othrinvstend));

        return parent::setOthrinvstend($othrinvstend);
    }

    /**
     * {@inheritDoc}
     */
    public function getOthrinvstend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOthrinvstend', array());

        return parent::getOthrinvstend();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaidcmpncd($paidcmpncd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaidcmpncd', array($paidcmpncd));

        return parent::setPaidcmpncd($paidcmpncd);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaidcmpncd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaidcmpncd', array());

        return parent::getPaidcmpncd();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropexchcd($propexchcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropexchcd', array($propexchcd));

        return parent::setPropexchcd($propexchcd);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropexchcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropexchcd', array());

        return parent::getPropexchcd();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropgndacd($propgndacd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropgndacd', array($propgndacd));

        return parent::setPropgndacd($propgndacd);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropgndacd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropgndacd', array());

        return parent::getPropgndacd();
    }

    /**
     * {@inheritDoc}
     */
    public function setPubsuprtcola($pubsuprtcola)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPubsuprtcola', array($pubsuprtcola));

        return parent::setPubsuprtcola($pubsuprtcola);
    }

    /**
     * {@inheritDoc}
     */
    public function getPubsuprtcola()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPubsuprtcola', array());

        return parent::getPubsuprtcola();
    }

    /**
     * {@inheritDoc}
     */
    public function setPubsuprtcolb($pubsuprtcolb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPubsuprtcolb', array($pubsuprtcolb));

        return parent::setPubsuprtcolb($pubsuprtcolb);
    }

    /**
     * {@inheritDoc}
     */
    public function getPubsuprtcolb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPubsuprtcolb', array());

        return parent::getPubsuprtcolb();
    }

    /**
     * {@inheritDoc}
     */
    public function setPubsuprtcolc($pubsuprtcolc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPubsuprtcolc', array($pubsuprtcolc));

        return parent::setPubsuprtcolc($pubsuprtcolc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPubsuprtcolc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPubsuprtcolc', array());

        return parent::getPubsuprtcolc();
    }

    /**
     * {@inheritDoc}
     */
    public function setPubsuprtcold($pubsuprtcold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPubsuprtcold', array($pubsuprtcold));

        return parent::setPubsuprtcold($pubsuprtcold);
    }

    /**
     * {@inheritDoc}
     */
    public function getPubsuprtcold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPubsuprtcold', array());

        return parent::getPubsuprtcold();
    }

    /**
     * {@inheritDoc}
     */
    public function setPubsuprttot($pubsuprttot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPubsuprttot', array($pubsuprttot));

        return parent::setPubsuprttot($pubsuprttot);
    }

    /**
     * {@inheritDoc}
     */
    public function getPubsuprttot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPubsuprttot', array());

        return parent::getPubsuprttot();
    }

    /**
     * {@inheritDoc}
     */
    public function setQlfyasseta($qlfyasseta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQlfyasseta', array($qlfyasseta));

        return parent::setQlfyasseta($qlfyasseta);
    }

    /**
     * {@inheritDoc}
     */
    public function getQlfyasseta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQlfyasseta', array());

        return parent::getQlfyasseta();
    }

    /**
     * {@inheritDoc}
     */
    public function setQlfyassetb($qlfyassetb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQlfyassetb', array($qlfyassetb));

        return parent::setQlfyassetb($qlfyassetb);
    }

    /**
     * {@inheritDoc}
     */
    public function getQlfyassetb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQlfyassetb', array());

        return parent::getQlfyassetb();
    }

    /**
     * {@inheritDoc}
     */
    public function setQlfyassetc($qlfyassetc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQlfyassetc', array($qlfyassetc));

        return parent::setQlfyassetc($qlfyassetc);
    }

    /**
     * {@inheritDoc}
     */
    public function getQlfyassetc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQlfyassetc', array());

        return parent::getQlfyassetc();
    }

    /**
     * {@inheritDoc}
     */
    public function setQlfyassetd($qlfyassetd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQlfyassetd', array($qlfyassetd));

        return parent::setQlfyassetd($qlfyassetd);
    }

    /**
     * {@inheritDoc}
     */
    public function getQlfyassetd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQlfyassetd', array());

        return parent::getQlfyassetd();
    }

    /**
     * {@inheritDoc}
     */
    public function setQlfyassettot($qlfyassettot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQlfyassettot', array($qlfyassettot));

        return parent::setQlfyassettot($qlfyassettot);
    }

    /**
     * {@inheritDoc}
     */
    public function getQlfyassettot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQlfyassettot', array());

        return parent::getQlfyassettot();
    }

    /**
     * {@inheritDoc}
     */
    public function setQlfydistriba($qlfydistriba)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQlfydistriba', array($qlfydistriba));

        return parent::setQlfydistriba($qlfydistriba);
    }

    /**
     * {@inheritDoc}
     */
    public function getQlfydistriba()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQlfydistriba', array());

        return parent::getQlfydistriba();
    }

    /**
     * {@inheritDoc}
     */
    public function setQlfydistribb($qlfydistribb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQlfydistribb', array($qlfydistribb));

        return parent::setQlfydistribb($qlfydistribb);
    }

    /**
     * {@inheritDoc}
     */
    public function getQlfydistribb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQlfydistribb', array());

        return parent::getQlfydistribb();
    }

    /**
     * {@inheritDoc}
     */
    public function setQlfydistribc($qlfydistribc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQlfydistribc', array($qlfydistribc));

        return parent::setQlfydistribc($qlfydistribc);
    }

    /**
     * {@inheritDoc}
     */
    public function getQlfydistribc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQlfydistribc', array());

        return parent::getQlfydistribc();
    }

    /**
     * {@inheritDoc}
     */
    public function setQlfydistribd($qlfydistribd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQlfydistribd', array($qlfydistribd));

        return parent::setQlfydistribd($qlfydistribd);
    }

    /**
     * {@inheritDoc}
     */
    public function getQlfydistribd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQlfydistribd', array());

        return parent::getQlfydistribd();
    }

    /**
     * {@inheritDoc}
     */
    public function setQlfydistribtot($qlfydistribtot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQlfydistribtot', array($qlfydistribtot));

        return parent::setQlfydistribtot($qlfydistribtot);
    }

    /**
     * {@inheritDoc}
     */
    public function getQlfydistribtot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQlfydistribtot', array());

        return parent::getQlfydistribtot();
    }

    /**
     * {@inheritDoc}
     */
    public function setSec4940notxcd($sec4940notxcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSec4940notxcd', array($sec4940notxcd));

        return parent::setSec4940notxcd($sec4940notxcd);
    }

    /**
     * {@inheritDoc}
     */
    public function getSec4940notxcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSec4940notxcd', array());

        return parent::getSec4940notxcd();
    }

    /**
     * {@inheritDoc}
     */
    public function setSec4940redtxcd($sec4940redtxcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSec4940redtxcd', array($sec4940redtxcd));

        return parent::setSec4940redtxcd($sec4940redtxcd);
    }

    /**
     * {@inheritDoc}
     */
    public function getSec4940redtxcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSec4940redtxcd', array());

        return parent::getSec4940redtxcd();
    }

    /**
     * {@inheritDoc}
     */
    public function setSect511tx($sect511tx)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSect511tx', array($sect511tx));

        return parent::setSect511tx($sect511tx);
    }

    /**
     * {@inheritDoc}
     */
    public function getSect511tx()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSect511tx', array());

        return parent::getSect511tx();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubcd($subcd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubcd', array($subcd));

        return parent::setSubcd($subcd);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubcd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubcd', array());

        return parent::getSubcd();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtitleatx($subtitleatx)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtitleatx', array($subtitleatx));

        return parent::setSubtitleatx($subtitleatx);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtitleatx()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtitleatx', array());

        return parent::getSubtitleatx();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxPrd($taxPrd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxPrd', array($taxPrd));

        return parent::setTaxPrd($taxPrd);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxPrd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxPrd', array());

        return parent::getTaxPrd();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxYr($taxYr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxYr', array($taxYr));

        return parent::setTaxYr($taxYr);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxYr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxYr', array());

        return parent::getTaxYr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTfairmrktunuse($tfairmrktunuse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTfairmrktunuse', array($tfairmrktunuse));

        return parent::setTfairmrktunuse($tfairmrktunuse);
    }

    /**
     * {@inheritDoc}
     */
    public function getTfairmrktunuse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTfairmrktunuse', array());

        return parent::getTfairmrktunuse();
    }

    /**
     * {@inheritDoc}
     */
    public function setTfundnworth($tfundnworth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTfundnworth', array($tfundnworth));

        return parent::setTfundnworth($tfundnworth);
    }

    /**
     * {@inheritDoc}
     */
    public function getTfundnworth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTfundnworth', array());

        return parent::getTfundnworth();
    }

    /**
     * {@inheritDoc}
     */
    public function setTopradmnexpnsa($topradmnexpnsa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTopradmnexpnsa', array($topradmnexpnsa));

        return parent::setTopradmnexpnsa($topradmnexpnsa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTopradmnexpnsa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTopradmnexpnsa', array());

        return parent::getTopradmnexpnsa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTopradmnexpnsb($topradmnexpnsb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTopradmnexpnsb', array($topradmnexpnsb));

        return parent::setTopradmnexpnsb($topradmnexpnsb);
    }

    /**
     * {@inheritDoc}
     */
    public function getTopradmnexpnsb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTopradmnexpnsb', array());

        return parent::getTopradmnexpnsb();
    }

    /**
     * {@inheritDoc}
     */
    public function setTopradmnexpnsd($topradmnexpnsd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTopradmnexpnsd', array($topradmnexpnsd));

        return parent::setTopradmnexpnsd($topradmnexpnsd);
    }

    /**
     * {@inheritDoc}
     */
    public function getTopradmnexpnsd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTopradmnexpnsd', array());

        return parent::getTopradmnexpnsd();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotassetsend($totassetsend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotassetsend', array($totassetsend));

        return parent::setTotassetsend($totassetsend);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotassetsend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotassetsend', array());

        return parent::getTotassetsend();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotaxpyr($totaxpyr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotaxpyr', array($totaxpyr));

        return parent::setTotaxpyr($totaxpyr);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotaxpyr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotaxpyr', array());

        return parent::getTotaxpyr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotexcapgn($totexcapgn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotexcapgn', array($totexcapgn));

        return parent::setTotexcapgn($totexcapgn);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotexcapgn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotexcapgn', array());

        return parent::getTotexcapgn();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotexcapls($totexcapls)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotexcapls', array($totexcapls));

        return parent::setTotexcapls($totexcapls);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotexcapls()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotexcapls', array());

        return parent::getTotexcapls();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotexpnsadjnet($totexpnsadjnet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotexpnsadjnet', array($totexpnsadjnet));

        return parent::setTotexpnsadjnet($totexpnsadjnet);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotexpnsadjnet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotexpnsadjnet', array());

        return parent::getTotexpnsadjnet();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotexpnsexempt($totexpnsexempt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotexpnsexempt', array($totexpnsexempt));

        return parent::setTotexpnsexempt($totexpnsexempt);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotexpnsexempt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotexpnsexempt', array());

        return parent::getTotexpnsexempt();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotexpnsnetinc($totexpnsnetinc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotexpnsnetinc', array($totexpnsnetinc));

        return parent::setTotexpnsnetinc($totexpnsnetinc);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotexpnsnetinc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotexpnsnetinc', array());

        return parent::getTotexpnsnetinc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotexpnspbks($totexpnspbks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotexpnspbks', array($totexpnspbks));

        return parent::setTotexpnspbks($totexpnspbks);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotexpnspbks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotexpnspbks', array());

        return parent::getTotexpnspbks();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotinvstsec($totinvstsec)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotinvstsec', array($totinvstsec));

        return parent::setTotinvstsec($totinvstsec);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotinvstsec()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotinvstsec', array());

        return parent::getTotinvstsec();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotliabend($totliabend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotliabend', array($totliabend));

        return parent::setTotliabend($totliabend);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotliabend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotliabend', array());

        return parent::getTotliabend();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotrcptnetinc($totrcptnetinc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotrcptnetinc', array($totrcptnetinc));

        return parent::setTotrcptnetinc($totrcptnetinc);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotrcptnetinc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotrcptnetinc', array());

        return parent::getTotrcptnetinc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotrcptperbks($totrcptperbks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotrcptperbks', array($totrcptperbks));

        return parent::setTotrcptperbks($totrcptperbks);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotrcptperbks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotrcptperbks', array());

        return parent::getTotrcptperbks();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotsuprtcola($totsuprtcola)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotsuprtcola', array($totsuprtcola));

        return parent::setTotsuprtcola($totsuprtcola);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotsuprtcola()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotsuprtcola', array());

        return parent::getTotsuprtcola();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotsuprtcolb($totsuprtcolb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotsuprtcolb', array($totsuprtcolb));

        return parent::setTotsuprtcolb($totsuprtcolb);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotsuprtcolb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotsuprtcolb', array());

        return parent::getTotsuprtcolb();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotsuprtcolc($totsuprtcolc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotsuprtcolc', array($totsuprtcolc));

        return parent::setTotsuprtcolc($totsuprtcolc);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotsuprtcolc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotsuprtcolc', array());

        return parent::getTotsuprtcolc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotsuprtcold($totsuprtcold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotsuprtcold', array($totsuprtcold));

        return parent::setTotsuprtcold($totsuprtcold);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotsuprtcold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotsuprtcold', array());

        return parent::getTotsuprtcold();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotsuprttot($totsuprttot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotsuprttot', array($totsuprttot));

        return parent::setTotsuprttot($totsuprttot);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotsuprttot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotsuprttot', array());

        return parent::getTotsuprttot();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransinccd($transinccd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransinccd', array($transinccd));

        return parent::setTransinccd($transinccd);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransinccd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransinccd', array());

        return parent::getTransinccd();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrcptadjnetinc($trcptadjnetinc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrcptadjnetinc', array($trcptadjnetinc));

        return parent::setTrcptadjnetinc($trcptadjnetinc);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrcptadjnetinc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrcptadjnetinc', array());

        return parent::getTrcptadjnetinc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrnsothasstscd($trnsothasstscd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrnsothasstscd', array($trnsothasstscd));

        return parent::setTrnsothasstscd($trnsothasstscd);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrnsothasstscd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrnsothasstscd', array());

        return parent::getTrnsothasstscd();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxpaidf2758($txpaidf2758)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxpaidf2758', array($txpaidf2758));

        return parent::setTxpaidf2758($txpaidf2758);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxpaidf2758()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxpaidf2758', array());

        return parent::getTxpaidf2758();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxwithldsrc($txwithldsrc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxwithldsrc', array($txwithldsrc));

        return parent::setTxwithldsrc($txwithldsrc);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxwithldsrc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxwithldsrc', array());

        return parent::getTxwithldsrc();
    }

    /**
     * {@inheritDoc}
     */
    public function setUndistribincyr($undistribincyr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUndistribincyr', array($undistribincyr));

        return parent::setUndistribincyr($undistribincyr);
    }

    /**
     * {@inheritDoc}
     */
    public function getUndistribincyr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUndistribincyr', array());

        return parent::getUndistribincyr();
    }

    /**
     * {@inheritDoc}
     */
    public function setUndistrinccd($undistrinccd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUndistrinccd', array($undistrinccd));

        return parent::setUndistrinccd($undistrinccd);
    }

    /**
     * {@inheritDoc}
     */
    public function getUndistrinccd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUndistrinccd', array());

        return parent::getUndistrinccd();
    }

    /**
     * {@inheritDoc}
     */
    public function setValassetscola($valassetscola)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValassetscola', array($valassetscola));

        return parent::setValassetscola($valassetscola);
    }

    /**
     * {@inheritDoc}
     */
    public function getValassetscola()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValassetscola', array());

        return parent::getValassetscola();
    }

    /**
     * {@inheritDoc}
     */
    public function setValassetscolb($valassetscolb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValassetscolb', array($valassetscolb));

        return parent::setValassetscolb($valassetscolb);
    }

    /**
     * {@inheritDoc}
     */
    public function getValassetscolb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValassetscolb', array());

        return parent::getValassetscolb();
    }

    /**
     * {@inheritDoc}
     */
    public function setValassetscolc($valassetscolc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValassetscolc', array($valassetscolc));

        return parent::setValassetscolc($valassetscolc);
    }

    /**
     * {@inheritDoc}
     */
    public function getValassetscolc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValassetscolc', array());

        return parent::getValassetscolc();
    }

    /**
     * {@inheritDoc}
     */
    public function setValassetscold($valassetscold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValassetscold', array($valassetscold));

        return parent::setValassetscold($valassetscold);
    }

    /**
     * {@inheritDoc}
     */
    public function getValassetscold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValassetscold', array());

        return parent::getValassetscold();
    }

    /**
     * {@inheritDoc}
     */
    public function setValassetstot($valassetstot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValassetstot', array($valassetstot));

        return parent::setValassetstot($valassetstot);
    }

    /**
     * {@inheritDoc}
     */
    public function getValassetstot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValassetstot', array());

        return parent::getValassetstot();
    }

    /**
     * {@inheritDoc}
     */
    public function get_class_without_namespace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_class_without_namespace', array());

        return parent::get_class_without_namespace();
    }

}
