<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PetitionSignature extends \Entity\PetitionSignature implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'user_id', 'signed_on', 'reason', 'petition_id', 'is_hide');
        }

        return array('__isInitialized__', 'id', 'user_id', 'signed_on', 'reason', 'petition_id', 'is_hide');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PetitionSignature $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($user_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', array($user_id));

        return parent::setUserId($user_id);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setReason($reason)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReason', array($reason));

        return parent::setReason($reason);
    }

    /**
     * {@inheritDoc}
     */
    public function getReason()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReason', array());

        return parent::getReason();
    }

    /**
     * {@inheritDoc}
     */
    public function setPetitionId($petition_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPetitionId', array($petition_id));

        return parent::setPetitionId($petition_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPetitionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPetitionId', array());

        return parent::getPetitionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPetition(\Entity\Petition $petition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPetition', array($petition));

        return parent::setPetition($petition);
    }

    /**
     * {@inheritDoc}
     */
    public function getPetition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPetition', array());

        return parent::getPetition();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignedOn($signed_on)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignedOn', array($signed_on));

        return parent::setSignedOn($signed_on);
    }

    /**
     * {@inheritDoc}
     */
    public function setSignedOnDt(\DateTime $signed_on)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignedOnDt', array($signed_on));

        return parent::setSignedOnDt($signed_on);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignedOn', array());

        return parent::getSignedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function getSignedOnDt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignedOnDt', array());

        return parent::getSignedOnDt();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsHide($hidden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsHide', array($hidden));

        return parent::setIsHide($hidden);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsHide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsHide', array());

        return parent::getIsHide();
    }

    /**
     * {@inheritDoc}
     */
    public function getIntervalFromNow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntervalFromNow', array());

        return parent::getIntervalFromNow();
    }

    /**
     * {@inheritDoc}
     */
    public function isHidden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isHidden', array());

        return parent::isHidden();
    }

    /**
     * {@inheritDoc}
     */
    public function getSignedAtDt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignedAtDt', array());

        return parent::getSignedAtDt();
    }

    /**
     * {@inheritDoc}
     */
    public function get_class_without_namespace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_class_without_namespace', array());

        return parent::get_class_without_namespace();
    }

}
