<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Irs2012990 extends \Entity\Irs2012990 implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'ein', 'taxPrd', 'subseccd', 'unrelbusinccd', 'initiationfees', 'grsrcptspublicuse', 'grsincmembers', 'grsincother', 'totcntrbgfts', 'totprgmrevnue', 'invstmntinc', 'txexmptbndsproceeds', 'royaltsinc', 'grsrntsreal', 'grsrntsprsnl', 'rntlexpnsreal', 'rntlexpnsprsnl', 'rntlincreal', 'rntlincprsnl', 'netrntlinc', 'grsalesecur', 'grsalesothr', 'cstbasisecur', 'cstbasisothr', 'gnlsecur', 'gnlsothr', 'netgnls', 'grsincfndrsng', 'lessdirfndrsng', 'netincfndrsng', 'grsincgaming', 'lessdirgaming', 'netincgaming', 'grsalesinvent', 'lesscstofgoods', 'netincsales', 'miscrevtot11e', 'totrevenue', 'compnsatncurrofcr', 'othrsalwages', 'payrolltx', 'profndraising', 'totfuncexpns', 'totassetsend', 'txexmptbndsend', 'secrdmrtgsend', 'unsecurednotesend', 'totliabend', 'retainedearnend', 'totnetassetend', 'nonpfrea', 'gftgrntsrcvd170', 'txrevnuelevied170', 'srvcsval170', 'grsinc170', 'grsrcptsrelated170', 'totgftgrntrcvd509', 'grsrcptsadmissn509', 'txrevnuelevied509', 'srvcsval509', 'subtotsuppinc509', 'totsupp509');
        }

        return array('__isInitialized__', 'id', 'ein', 'taxPrd', 'subseccd', 'unrelbusinccd', 'initiationfees', 'grsrcptspublicuse', 'grsincmembers', 'grsincother', 'totcntrbgfts', 'totprgmrevnue', 'invstmntinc', 'txexmptbndsproceeds', 'royaltsinc', 'grsrntsreal', 'grsrntsprsnl', 'rntlexpnsreal', 'rntlexpnsprsnl', 'rntlincreal', 'rntlincprsnl', 'netrntlinc', 'grsalesecur', 'grsalesothr', 'cstbasisecur', 'cstbasisothr', 'gnlsecur', 'gnlsothr', 'netgnls', 'grsincfndrsng', 'lessdirfndrsng', 'netincfndrsng', 'grsincgaming', 'lessdirgaming', 'netincgaming', 'grsalesinvent', 'lesscstofgoods', 'netincsales', 'miscrevtot11e', 'totrevenue', 'compnsatncurrofcr', 'othrsalwages', 'payrolltx', 'profndraising', 'totfuncexpns', 'totassetsend', 'txexmptbndsend', 'secrdmrtgsend', 'unsecurednotesend', 'totliabend', 'retainedearnend', 'totnetassetend', 'nonpfrea', 'gftgrntsrcvd170', 'txrevnuelevied170', 'srvcsval170', 'grsinc170', 'grsrcptsrelated170', 'totgftgrntrcvd509', 'grsrcptsadmissn509', 'txrevnuelevied509', 'srvcsval509', 'subtotsuppinc509', 'totsupp509');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Irs2012990 $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCompnsatncurrofcr($compnsatncurrofcr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompnsatncurrofcr', array($compnsatncurrofcr));

        return parent::setCompnsatncurrofcr($compnsatncurrofcr);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompnsatncurrofcr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompnsatncurrofcr', array());

        return parent::getCompnsatncurrofcr();
    }

    /**
     * {@inheritDoc}
     */
    public function setCstbasisecur($cstbasisecur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCstbasisecur', array($cstbasisecur));

        return parent::setCstbasisecur($cstbasisecur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCstbasisecur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCstbasisecur', array());

        return parent::getCstbasisecur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCstbasisothr($cstbasisothr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCstbasisothr', array($cstbasisothr));

        return parent::setCstbasisothr($cstbasisothr);
    }

    /**
     * {@inheritDoc}
     */
    public function getCstbasisothr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCstbasisothr', array());

        return parent::getCstbasisothr();
    }

    /**
     * {@inheritDoc}
     */
    public function setEin($ein)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEin', array($ein));

        return parent::setEin($ein);
    }

    /**
     * {@inheritDoc}
     */
    public function getEin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEin', array());

        return parent::getEin();
    }

    /**
     * {@inheritDoc}
     */
    public function setGftgrntsrcvd170($gftgrntsrcvd170)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGftgrntsrcvd170', array($gftgrntsrcvd170));

        return parent::setGftgrntsrcvd170($gftgrntsrcvd170);
    }

    /**
     * {@inheritDoc}
     */
    public function getGftgrntsrcvd170()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGftgrntsrcvd170', array());

        return parent::getGftgrntsrcvd170();
    }

    /**
     * {@inheritDoc}
     */
    public function setGnlsecur($gnlsecur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGnlsecur', array($gnlsecur));

        return parent::setGnlsecur($gnlsecur);
    }

    /**
     * {@inheritDoc}
     */
    public function getGnlsecur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGnlsecur', array());

        return parent::getGnlsecur();
    }

    /**
     * {@inheritDoc}
     */
    public function setGnlsothr($gnlsothr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGnlsothr', array($gnlsothr));

        return parent::setGnlsothr($gnlsothr);
    }

    /**
     * {@inheritDoc}
     */
    public function getGnlsothr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGnlsothr', array());

        return parent::getGnlsothr();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsalesecur($grsalesecur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsalesecur', array($grsalesecur));

        return parent::setGrsalesecur($grsalesecur);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsalesecur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsalesecur', array());

        return parent::getGrsalesecur();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsalesinvent($grsalesinvent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsalesinvent', array($grsalesinvent));

        return parent::setGrsalesinvent($grsalesinvent);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsalesinvent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsalesinvent', array());

        return parent::getGrsalesinvent();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsalesothr($grsalesothr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsalesothr', array($grsalesothr));

        return parent::setGrsalesothr($grsalesothr);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsalesothr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsalesothr', array());

        return parent::getGrsalesothr();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsinc170($grsinc170)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsinc170', array($grsinc170));

        return parent::setGrsinc170($grsinc170);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsinc170()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsinc170', array());

        return parent::getGrsinc170();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsincfndrsng($grsincfndrsng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsincfndrsng', array($grsincfndrsng));

        return parent::setGrsincfndrsng($grsincfndrsng);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsincfndrsng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsincfndrsng', array());

        return parent::getGrsincfndrsng();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsincgaming($grsincgaming)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsincgaming', array($grsincgaming));

        return parent::setGrsincgaming($grsincgaming);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsincgaming()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsincgaming', array());

        return parent::getGrsincgaming();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsincmembers($grsincmembers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsincmembers', array($grsincmembers));

        return parent::setGrsincmembers($grsincmembers);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsincmembers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsincmembers', array());

        return parent::getGrsincmembers();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsincother($grsincother)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsincother', array($grsincother));

        return parent::setGrsincother($grsincother);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsincother()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsincother', array());

        return parent::getGrsincother();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsrcptsadmissn509($grsrcptsadmissn509)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsrcptsadmissn509', array($grsrcptsadmissn509));

        return parent::setGrsrcptsadmissn509($grsrcptsadmissn509);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsrcptsadmissn509()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsrcptsadmissn509', array());

        return parent::getGrsrcptsadmissn509();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsrcptspublicuse($grsrcptspublicuse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsrcptspublicuse', array($grsrcptspublicuse));

        return parent::setGrsrcptspublicuse($grsrcptspublicuse);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsrcptspublicuse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsrcptspublicuse', array());

        return parent::getGrsrcptspublicuse();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsrcptsrelated170($grsrcptsrelated170)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsrcptsrelated170', array($grsrcptsrelated170));

        return parent::setGrsrcptsrelated170($grsrcptsrelated170);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsrcptsrelated170()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsrcptsrelated170', array());

        return parent::getGrsrcptsrelated170();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsrntsprsnl($grsrntsprsnl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsrntsprsnl', array($grsrntsprsnl));

        return parent::setGrsrntsprsnl($grsrntsprsnl);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsrntsprsnl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsrntsprsnl', array());

        return parent::getGrsrntsprsnl();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrsrntsreal($grsrntsreal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrsrntsreal', array($grsrntsreal));

        return parent::setGrsrntsreal($grsrntsreal);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrsrntsreal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrsrntsreal', array());

        return parent::getGrsrntsreal();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitiationfees($initiationfees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitiationfees', array($initiationfees));

        return parent::setInitiationfees($initiationfees);
    }

    /**
     * {@inheritDoc}
     */
    public function getInitiationfees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitiationfees', array());

        return parent::getInitiationfees();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvstmntinc($invstmntinc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvstmntinc', array($invstmntinc));

        return parent::setInvstmntinc($invstmntinc);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvstmntinc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvstmntinc', array());

        return parent::getInvstmntinc();
    }

    /**
     * {@inheritDoc}
     */
    public function setLesscstofgoods($lesscstofgoods)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLesscstofgoods', array($lesscstofgoods));

        return parent::setLesscstofgoods($lesscstofgoods);
    }

    /**
     * {@inheritDoc}
     */
    public function getLesscstofgoods()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLesscstofgoods', array());

        return parent::getLesscstofgoods();
    }

    /**
     * {@inheritDoc}
     */
    public function setLessdirfndrsng($lessdirfndrsng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLessdirfndrsng', array($lessdirfndrsng));

        return parent::setLessdirfndrsng($lessdirfndrsng);
    }

    /**
     * {@inheritDoc}
     */
    public function getLessdirfndrsng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLessdirfndrsng', array());

        return parent::getLessdirfndrsng();
    }

    /**
     * {@inheritDoc}
     */
    public function setLessdirgaming($lessdirgaming)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLessdirgaming', array($lessdirgaming));

        return parent::setLessdirgaming($lessdirgaming);
    }

    /**
     * {@inheritDoc}
     */
    public function getLessdirgaming()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLessdirgaming', array());

        return parent::getLessdirgaming();
    }

    /**
     * {@inheritDoc}
     */
    public function setMiscrevtot11e($miscrevtot11e)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiscrevtot11e', array($miscrevtot11e));

        return parent::setMiscrevtot11e($miscrevtot11e);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiscrevtot11e()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiscrevtot11e', array());

        return parent::getMiscrevtot11e();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetgnls($netgnls)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetgnls', array($netgnls));

        return parent::setNetgnls($netgnls);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetgnls()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetgnls', array());

        return parent::getNetgnls();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetincfndrsng($netincfndrsng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetincfndrsng', array($netincfndrsng));

        return parent::setNetincfndrsng($netincfndrsng);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetincfndrsng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetincfndrsng', array());

        return parent::getNetincfndrsng();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetincgaming($netincgaming)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetincgaming', array($netincgaming));

        return parent::setNetincgaming($netincgaming);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetincgaming()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetincgaming', array());

        return parent::getNetincgaming();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetincsales($netincsales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetincsales', array($netincsales));

        return parent::setNetincsales($netincsales);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetincsales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetincsales', array());

        return parent::getNetincsales();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetrntlinc($netrntlinc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetrntlinc', array($netrntlinc));

        return parent::setNetrntlinc($netrntlinc);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetrntlinc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetrntlinc', array());

        return parent::getNetrntlinc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNonpfrea($nonpfrea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNonpfrea', array($nonpfrea));

        return parent::setNonpfrea($nonpfrea);
    }

    /**
     * {@inheritDoc}
     */
    public function getNonpfrea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNonpfrea', array());

        return parent::getNonpfrea();
    }

    /**
     * {@inheritDoc}
     */
    public function setOthrsalwages($othrsalwages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOthrsalwages', array($othrsalwages));

        return parent::setOthrsalwages($othrsalwages);
    }

    /**
     * {@inheritDoc}
     */
    public function getOthrsalwages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOthrsalwages', array());

        return parent::getOthrsalwages();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayrolltx($payrolltx)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayrolltx', array($payrolltx));

        return parent::setPayrolltx($payrolltx);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayrolltx()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayrolltx', array());

        return parent::getPayrolltx();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfndraising($profndraising)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfndraising', array($profndraising));

        return parent::setProfndraising($profndraising);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfndraising()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfndraising', array());

        return parent::getProfndraising();
    }

    /**
     * {@inheritDoc}
     */
    public function setRetainedearnend($retainedearnend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRetainedearnend', array($retainedearnend));

        return parent::setRetainedearnend($retainedearnend);
    }

    /**
     * {@inheritDoc}
     */
    public function getRetainedearnend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRetainedearnend', array());

        return parent::getRetainedearnend();
    }

    /**
     * {@inheritDoc}
     */
    public function setRntlexpnsprsnl($rntlexpnsprsnl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRntlexpnsprsnl', array($rntlexpnsprsnl));

        return parent::setRntlexpnsprsnl($rntlexpnsprsnl);
    }

    /**
     * {@inheritDoc}
     */
    public function getRntlexpnsprsnl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRntlexpnsprsnl', array());

        return parent::getRntlexpnsprsnl();
    }

    /**
     * {@inheritDoc}
     */
    public function setRntlexpnsreal($rntlexpnsreal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRntlexpnsreal', array($rntlexpnsreal));

        return parent::setRntlexpnsreal($rntlexpnsreal);
    }

    /**
     * {@inheritDoc}
     */
    public function getRntlexpnsreal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRntlexpnsreal', array());

        return parent::getRntlexpnsreal();
    }

    /**
     * {@inheritDoc}
     */
    public function setRntlincprsnl($rntlincprsnl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRntlincprsnl', array($rntlincprsnl));

        return parent::setRntlincprsnl($rntlincprsnl);
    }

    /**
     * {@inheritDoc}
     */
    public function getRntlincprsnl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRntlincprsnl', array());

        return parent::getRntlincprsnl();
    }

    /**
     * {@inheritDoc}
     */
    public function setRntlincreal($rntlincreal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRntlincreal', array($rntlincreal));

        return parent::setRntlincreal($rntlincreal);
    }

    /**
     * {@inheritDoc}
     */
    public function getRntlincreal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRntlincreal', array());

        return parent::getRntlincreal();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoyaltsinc($royaltsinc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoyaltsinc', array($royaltsinc));

        return parent::setRoyaltsinc($royaltsinc);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoyaltsinc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoyaltsinc', array());

        return parent::getRoyaltsinc();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecrdmrtgsend($secrdmrtgsend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecrdmrtgsend', array($secrdmrtgsend));

        return parent::setSecrdmrtgsend($secrdmrtgsend);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecrdmrtgsend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecrdmrtgsend', array());

        return parent::getSecrdmrtgsend();
    }

    /**
     * {@inheritDoc}
     */
    public function setSrvcsval170($srvcsval170)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSrvcsval170', array($srvcsval170));

        return parent::setSrvcsval170($srvcsval170);
    }

    /**
     * {@inheritDoc}
     */
    public function getSrvcsval170()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSrvcsval170', array());

        return parent::getSrvcsval170();
    }

    /**
     * {@inheritDoc}
     */
    public function setSrvcsval509($srvcsval509)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSrvcsval509', array($srvcsval509));

        return parent::setSrvcsval509($srvcsval509);
    }

    /**
     * {@inheritDoc}
     */
    public function getSrvcsval509()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSrvcsval509', array());

        return parent::getSrvcsval509();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubseccd($subseccd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubseccd', array($subseccd));

        return parent::setSubseccd($subseccd);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubseccd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubseccd', array());

        return parent::getSubseccd();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotsuppinc509($subtotsuppinc509)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotsuppinc509', array($subtotsuppinc509));

        return parent::setSubtotsuppinc509($subtotsuppinc509);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotsuppinc509()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotsuppinc509', array());

        return parent::getSubtotsuppinc509();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxPrd($taxPrd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxPrd', array($taxPrd));

        return parent::setTaxPrd($taxPrd);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxPrd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxPrd', array());

        return parent::getTaxPrd();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotassetsend($totassetsend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotassetsend', array($totassetsend));

        return parent::setTotassetsend($totassetsend);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotassetsend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotassetsend', array());

        return parent::getTotassetsend();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotcntrbgfts($totcntrbgfts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotcntrbgfts', array($totcntrbgfts));

        return parent::setTotcntrbgfts($totcntrbgfts);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotcntrbgfts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotcntrbgfts', array());

        return parent::getTotcntrbgfts();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotfuncexpns($totfuncexpns)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotfuncexpns', array($totfuncexpns));

        return parent::setTotfuncexpns($totfuncexpns);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotfuncexpns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotfuncexpns', array());

        return parent::getTotfuncexpns();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotgftgrntrcvd509($totgftgrntrcvd509)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotgftgrntrcvd509', array($totgftgrntrcvd509));

        return parent::setTotgftgrntrcvd509($totgftgrntrcvd509);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotgftgrntrcvd509()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotgftgrntrcvd509', array());

        return parent::getTotgftgrntrcvd509();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotliabend($totliabend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotliabend', array($totliabend));

        return parent::setTotliabend($totliabend);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotliabend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotliabend', array());

        return parent::getTotliabend();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotnetassetend($totnetassetend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotnetassetend', array($totnetassetend));

        return parent::setTotnetassetend($totnetassetend);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotnetassetend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotnetassetend', array());

        return parent::getTotnetassetend();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotprgmrevnue($totprgmrevnue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotprgmrevnue', array($totprgmrevnue));

        return parent::setTotprgmrevnue($totprgmrevnue);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotprgmrevnue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotprgmrevnue', array());

        return parent::getTotprgmrevnue();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotrevenue($totrevenue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotrevenue', array($totrevenue));

        return parent::setTotrevenue($totrevenue);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotrevenue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotrevenue', array());

        return parent::getTotrevenue();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotsupp509($totsupp509)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotsupp509', array($totsupp509));

        return parent::setTotsupp509($totsupp509);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotsupp509()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotsupp509', array());

        return parent::getTotsupp509();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxexmptbndsend($txexmptbndsend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxexmptbndsend', array($txexmptbndsend));

        return parent::setTxexmptbndsend($txexmptbndsend);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxexmptbndsend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxexmptbndsend', array());

        return parent::getTxexmptbndsend();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxexmptbndsproceeds($txexmptbndsproceeds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxexmptbndsproceeds', array($txexmptbndsproceeds));

        return parent::setTxexmptbndsproceeds($txexmptbndsproceeds);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxexmptbndsproceeds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxexmptbndsproceeds', array());

        return parent::getTxexmptbndsproceeds();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxrevnuelevied170($txrevnuelevied170)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxrevnuelevied170', array($txrevnuelevied170));

        return parent::setTxrevnuelevied170($txrevnuelevied170);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxrevnuelevied170()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxrevnuelevied170', array());

        return parent::getTxrevnuelevied170();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxrevnuelevied509($txrevnuelevied509)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxrevnuelevied509', array($txrevnuelevied509));

        return parent::setTxrevnuelevied509($txrevnuelevied509);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxrevnuelevied509()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxrevnuelevied509', array());

        return parent::getTxrevnuelevied509();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnrelbusinccd($unrelbusinccd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnrelbusinccd', array($unrelbusinccd));

        return parent::setUnrelbusinccd($unrelbusinccd);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnrelbusinccd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnrelbusinccd', array());

        return parent::getUnrelbusinccd();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnsecurednotesend($unsecurednotesend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnsecurednotesend', array($unsecurednotesend));

        return parent::setUnsecurednotesend($unsecurednotesend);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnsecurednotesend()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnsecurednotesend', array());

        return parent::getUnsecurednotesend();
    }

    /**
     * {@inheritDoc}
     */
    public function get_class_without_namespace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'get_class_without_namespace', array());

        return parent::get_class_without_namespace();
    }

}
